name: staging and production deploy
run-name: ${{ github.actor }} has run the stg-prod-deploy trigger

on:
  push:
    tags:
      - 'release-*'

jobs:
  staging-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      GH-ENV: staging
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  production-deploy:
    # Staging deploy must succeed before a Production deploy can start
    needs: staging-deploy
    uses: ./.github/workflows/deploy.yml
    with:
      GH-ENV: production
    secrets: inherit
    permissions:
      id-token: write
      contents: read
