name: staging and production deploy
run-name: ${{ github.actor }} has run the stg-prod-deploy trigger

on:
  push:
    tags:
      - 'release-*'

jobs:
  staging-deploy:
    uses: ./.github/workflows/reusable/deploy.yml
    with:
      gh-environment: staging
    secrets: inherit

  production-deploy:
    # Staging deploy must succeed before a Production deploy can start
    needs: staging-deploy
    uses: ./.github/workflows/reusable/deploy.yml
    with:
      gh-environment: production
    secrets: inherit
